// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type CreateOrder struct {
	OrderCode   string `json:"orderCode"`
	OrderType   string `json:"orderType"`
	Products    string `json:"products"`
	OrderStatus string `json:"orderStatus"`
	Quantity    int    `json:"quantity"`
	TotalPrice  int    `json:"totalPrice"`
}

type CreateProduct struct {
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
	Price       int    `json:"price"`
}

type DeleteOrder struct {
	ID int `json:"id"`
}

type DeleteProduct struct {
	ID int `json:"id"`
}

type Order struct {
	ID          *int    `json:"id"`
	OrderCode   *string `json:"orderCode"`
	OrderType   *string `json:"orderType"`
	Products    *string `json:"products"`
	OrderStatus *string `json:"orderStatus"`
	Quantity    *int    `json:"quantity"`
	TotalPrice  *int    `json:"totalPrice"`
	CreatedAt   *string `json:"createdAt"`
	UpdatedAt   *string `json:"updatedAt"`
}

type Product struct {
	ID          *int    `json:"id"`
	ProductCode *string `json:"productCode"`
	ProductName *string `json:"productName"`
	Price       *int    `json:"price"`
	CreatedAt   *string `json:"createdAt"`
	UpdatedAt   *string `json:"updatedAt"`
}
